version: "3.9"

services:
  web:
    container_name: django
    build: ./parser_project
    command: python /code/parser_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  app:
    container_name: parser
    build: ./sheets_parsing
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
