# Generated by Django 4.1.1 on 2022-09-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParserListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.CharField(blank=True, db_column='№', max_length=50, null=True)),
                ('order_N', models.CharField(blank=True, db_column='заказ №', max_length=50, null=True)),
                ('price_dol', models.CharField(blank=True, db_column='стоимость,$', max_length=50, null=True)),
                ('date', models.CharField(blank=True, db_column='срок поставки', max_length=50, null=True)),
                ('price_rub', models.CharField(blank=True, db_column='стоимость в руб.', max_length=50, null=True)),
            ],
            options={
                'db_table': 'test777',
                'managed': False,
            },
        ),
    ]
